### PR TITLE
Fix #23: GHC-9.2 compilation failure due to change in ghc-prim

### LINKED ISSUE #23: GHC 9.2 alpha2 build failure
Attempting to compile with GHC 9.2 alpha-2 (and `--allow-newer`) gives this error:
```
[ 9 of 11] Compiling Blaze.ByteString.Builder.HTTP ( Blaze/ByteString/Builder/HTTP.hs, dist/build/Blaze/ByteString/Builder/HTTP.o, dist/build/Blaze/ByteString/Builder/HTTP.dyn_o )

Blaze/ByteString/Builder/HTTP.hs:52:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W32# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w32’:
          shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#` i)
   |
52 | shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```
See migration guide at https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2.

### PR DESCRIPTION
**Pull request by andreasabel**
Fix #23: GHC-9.2 compilation failure due to change in ghc-prim

The type of `uncheckedShiftRL#` changed in ghc-prim-0.8.0.

The fix is taken from the GHC testsuite, see:

  https://gitlab.haskell.org/ghc/ghc/-/blob/100ffe75f509a73f1b26e768237888646f522b6c/testsuite/tests/profiling/should_run/T3001-2.hs#L159-160

To get the `MIN_VERSION_ghc_prim` macro, `ghc-prim` needs to be added
to the explicit dependencies in the cabal file.

### CODE REVIEW

**Comment by andreasabel** [comment]
ATTN @lpsmith

**Comment by andreasabel** [comment]
ping @lpsmith (owner) @jaspervdj (last committer and uploader)

**Comment by andreasabel** [comment]
Maintenance moved to https://github.com/blaze-builder/blaze-builder
