### ISSUE TITLE
GHC 9.2 alpha2 build failure

### ISSUE THREAD

**Issue by andreasabel** [lpsmith/blaze-builder#23]
Attempting to compile with GHC 9.2 alpha-2 (and `--allow-newer`) gives this error:
```
[ 9 of 11] Compiling Blaze.ByteString.Builder.HTTP ( Blaze/ByteString/Builder/HTTP.hs, dist/build/Blaze/ByteString/Builder/HTTP.o, dist/build/Blaze/ByteString/Builder/HTTP.dyn_o )

Blaze/ByteString/Builder/HTTP.hs:52:36: error:
    • Couldn't match expected type ‘Word32#’ with actual type ‘Word#’
    • In the first argument of ‘W32#’, namely
        ‘(w `uncheckedShiftRL#` i)’
      In the expression: W32# (w `uncheckedShiftRL#` i)
      In an equation for ‘shiftr_w32’:
          shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#` i)
   |
52 | shiftr_w32 (W32# w) (I# i) = W32# (w `uncheckedShiftRL#`   i)
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^
```
See migration guide at https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2.

**Comment by andreasabel** [comment]
Blocking 
- https://github.com/agda/agda/issues/5442.

**Comment by andreasabel** [comment]
Maintenance moved to https://github.com/blaze-builder/blaze-builder

**Comment by Bodigrim** [comment]
As a Hackage trustee, I made a revision:
https://hackage.haskell.org/package/blaze-builder-0.4.2.1/revisions/
